set(CMAKE_SYSTEM_VERSION 7.0)

if(CMAKE_VERSION VERSION_LESS "3.15")
  message(FATAL_ERROR "Minimum CMake 3.15 is required (got ${CMAKE_VERSION})")
endif()

add_compile_definitions(${PROJECT_NAME} PRIVATE _WIN32_WINNT=0x0501)

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
